name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  cli-gitpod:
    name: CLI and Gitpod Demo
    runs-on: ubuntu-latest
    steps:
    - name: Hello From Gitpod
      run: |
        echo "Hello! From Gitpod 🍊"
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.17'

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      run: go test ./...
